import { useState } from 'react'
import type { CodeArtifact } from '@akis/shared'
import type { ApiClient } from '../api/client.js'
import { SectionTitle, Button, Input, ErrorNote } from '../ui/kit.js'
import { useI18n } from '../i18n/I18nContext.js'
import { ApiError } from '../api/client.js'

/** Gate-safe external publishing for a finished build: PROPOSE a Jira issue / Confluence page, review
 *  the exact summary + digest, then CONFIRM to execute via the user's own MCP connection. The write
 *  never fires without this explicit human confirm; "not connected" is surfaced, never a silent no-op. */
type Mode = { kind: 'confluence' | 'jira' } & ({ step: 'form' } | { step: 'review'; id: string; digest: string; summary: string } | { step: 'done'; result: string; ok: boolean })

export function ExternalWriteCard({ sessionId, idea, files, api }: { sessionId: string; idea: string; files: CodeArtifact['files'] | undefined; api: ApiClient }) {
  const { t } = useI18n()
  const [mode, setMode] = useState<Mode | undefined>()
  const [key, setKey] = useState('')
  const [busy, setBusy] = useState(false)
  const [err, setErr] = useState<string | undefined>()

  const title = (idea.split('\n')[0] || 'AKIS build').replace(/^#\s*/, '').slice(0, 120)
  const readme = files?.find(f => /readme\.md$/i.test(f.filePath))?.content ?? `# ${title}\n\nGenerated by AKIS.`

  const open = (kind: 'confluence' | 'jira'): void => { setMode({ kind, step: 'form' }); setKey(''); setErr(undefined) }

  const propose = async (): Promise<void> => {
    if (!mode || mode.step !== 'form' || !key.trim()) return
    setBusy(true); setErr(undefined)
    const body = mode.kind === 'confluence'
      ? { provider: 'atlassian', action: 'createPage', summary: `Create Confluence page “${title}” in ${key}`, target: { spaceKey: key.trim() }, payload: { title, body: readme } }
      : { provider: 'atlassian', action: 'createJiraIssue', summary: `Create Jira issue “${title}” in ${key}`, target: { projectKey: key.trim() }, payload: { summary: title, description: readme } }
    try {
      const r = await api.proposeExternalWrite(sessionId, body)
      setMode({ kind: mode.kind, step: 'review', id: r.id, digest: r.digest, summary: r.summary })
    } catch (e) { setErr(ApiError.is(e) ? e.message : String(e)) }
    finally { setBusy(false) }
  }

  const confirm = async (): Promise<void> => {
    if (!mode || mode.step !== 'review') return
    setBusy(true); setErr(undefined)
    try {
      const r = await api.confirmExternalWrite(sessionId, mode.id, mode.digest)
      setMode({ kind: mode.kind, step: 'done', ok: r.ok, result: r.result ?? (r.ok ? 'done' : 'failed') })
    } catch (e) {
      // A 409 = not connected / unavailable — guide the user to Settings.
      setErr(ApiError.is(e) && e.status === 409 ? t('mcpwrite.notConnected') : ApiError.is(e) ? e.message : String(e))
    } finally { setBusy(false) }
  }

  return (
    <div className="rounded-2xl border border-white/10 bg-white/[0.02] p-4">
      <SectionTitle sub={t('mcpwrite.sub')}>{t('mcpwrite.title')}</SectionTitle>
      {err && <div className="my-2"><ErrorNote>{err}</ErrorNote></div>}

      {!mode && (
        <div className="flex gap-2">
          <Button variant="ghost" onClick={() => open('confluence')}>{t('mcpwrite.toConfluence')}</Button>
          <Button variant="ghost" onClick={() => open('jira')}>{t('mcpwrite.toJira')}</Button>
        </div>
      )}

      {mode?.step === 'form' && (
        <div className="flex flex-col gap-2">
          <Input value={key} onChange={e => setKey(e.target.value)} placeholder={mode.kind === 'confluence' ? t('mcpwrite.spaceKey') : t('mcpwrite.projectKey')} />
          <div className="flex gap-2">
            <Button onClick={() => void propose()} disabled={busy || !key.trim()}>{busy ? '…' : t('mcpwrite.propose')}</Button>
            <Button variant="ghost" onClick={() => setMode(undefined)}>{t('mcpwrite.cancel')}</Button>
          </div>
        </div>
      )}

      {mode?.step === 'review' && (
        <div className="flex flex-col gap-2">
          <div className="text-sm text-slate-200">{mode.summary}</div>
          <div className="text-xs text-slate-500">{t('mcpwrite.digest')}: <code>{mode.digest.slice(0, 16)}…</code></div>
          <div className="flex gap-2">
            <Button onClick={() => void confirm()} disabled={busy}>{busy ? '…' : t('mcpwrite.confirm')}</Button>
            <Button variant="ghost" onClick={() => setMode(undefined)}>{t('mcpwrite.cancel')}</Button>
          </div>
        </div>
      )}

      {mode?.step === 'done' && (
        <div role="status" className={`rounded-lg border px-3 py-2 text-sm ${mode.ok ? 'border-[#07D1AF]/30 bg-[#07D1AF]/10 text-[#07D1AF]' : 'border-rose-400/30 bg-rose-400/10 text-rose-300'}`}>
          {mode.ok ? t('mcpwrite.created') : t('mcpwrite.failed')}: {mode.result.slice(0, 200)}
        </div>
      )}
    </div>
  )
}
