import { useState, useEffect, useCallback } from 'react'
import type { CodeArtifact } from '@akis/shared'
import type { ApiClient, ExternalWriteSummary } from '../api/client.js'
import { SectionTitle, Button, Input, ErrorNote } from '../ui/kit.js'
import { useI18n } from '../i18n/I18nContext.js'
import { ApiError } from '../api/client.js'
import { Link } from '../router/router.js'

/** Gate-safe external publishing for a finished build: PROPOSE a Jira issue / Confluence page, review
 *  the exact target + payload bytes + digest, then CONFIRM to execute via the user's own MCP
 *  connection. The write never fires without this explicit human confirm. The card is CONNECTION-AWARE
 *  — if Atlassian isn't connected it guides the user to Settings instead of letting them hit a
 *  confirm-time 409 — and shows the history of past proposals + outcomes. */
type Proposal = { target: Record<string, unknown>; payload: Record<string, unknown> }
type Mode = { kind: 'confluence' | 'jira' } & (
  | { step: 'form' }
  | ({ step: 'review'; id: string; digest: string; summary: string } & Proposal)
  | { step: 'done'; result: string; ok: boolean }
)

/** Atlassian OAuth scope that actually permits createPage. The connected app's granted scopes were
 *  reduced to JIRA-ONLY (owner decision 2026-06-08), so WITHOUT this scope a Confluence proposal
 *  would mint, the user would confirm, then Atlassian REJECTS it at execution. We therefore OFFER the
 *  Confluence action only when the live grant includes it — data-driven, so it auto-restores the
 *  moment the scope is re-added to the app, with no client-side hard-coding of "Confluence off". */
const CONFLUENCE_WRITE_SCOPE = 'write:confluence-content'

export function ExternalWriteCard({ sessionId, idea, files, api }: { sessionId: string; idea: string; files: CodeArtifact['files'] | undefined; api: ApiClient }) {
  const { t } = useI18n()
  const [mode, setMode] = useState<Mode | undefined>()
  const [key, setKey] = useState('')
  const [busy, setBusy] = useState(false)
  const [err, setErr] = useState<string | undefined>()
  // undefined = still loading; the card hides its actions until it knows the connection state.
  const [connected, setConnected] = useState<boolean | undefined>(undefined)
  // The live granted-scope string from /mcp/atlassian/status (space-separated). undefined while
  // loading / on error → we FAIL SAFE and treat Confluence as unavailable until we positively see it.
  const [scopes, setScopes] = useState<string | undefined>(undefined)
  const [history, setHistory] = useState<ExternalWriteSummary[]>([])
  // Only OFFER createPage when the connection's live grant actually permits it (see scope const).
  const confluenceAvailable = scopes?.split(/\s+/).includes(CONFLUENCE_WRITE_SCOPE) ?? false

  const title = (idea.split('\n')[0] || t('mcpwrite.untitledBuild')).replace(/^#\s*/, '').slice(0, 120)
  const readme = files?.find(f => /readme\.md$/i.test(f.filePath))?.content ?? `# ${title}\n\nGenerated by AKIS.`

  // Promise.resolve().then(call) so a SYNCHRONOUS throw (e.g. a partial mock missing the method, or
  // an older api) becomes a rejected promise the .catch handles — the card degrades, never crashes.
  const loadHistory = useCallback((): void => {
    // DROP github proposed writes — those are OWNED by AgentWriteProposals (the confirm surface), so a
    // status:'proposed' github write would otherwise double-render (here as a read-only history line AND
    // there as a confirm card). Executed/failed github writes still belong in history.
    const ownedByProposals = (w: ExternalWriteSummary): boolean => w.provider === 'github' && w.status === 'proposed'
    Promise.resolve().then(() => api.listExternalWrites(sessionId)).then(r => setHistory(Array.isArray(r?.writes) ? r.writes.filter(w => !ownedByProposals(w)) : [])).catch(() => {})
  }, [api, sessionId])

  useEffect(() => {
    Promise.resolve().then(() => api.mcpStatus('atlassian')).then(s => { setConnected(s?.connected === true); setScopes(typeof s?.scopes === 'string' ? s.scopes : undefined) }).catch(() => { setConnected(false); setScopes(undefined) })
    loadHistory()
  }, [api, loadHistory])

  const open = (kind: 'confluence' | 'jira'): void => { setMode({ kind, step: 'form' }); setKey(''); setErr(undefined) }

  const propose = async (): Promise<void> => {
    if (!mode || mode.step !== 'form' || !key.trim()) return
    setBusy(true); setErr(undefined)
    // The human-confirm prompt (summary) is localized via the translatable verb prefix; title + key
    // are user data (not translatable). The digest binds action/target/payload, not this text.
    const body = mode.kind === 'confluence'
      ? { provider: 'atlassian', action: 'createPage', summary: `${t('mcpwrite.toConfluence')}: “${title}” (${key.trim()})`, target: { spaceKey: key.trim() }, payload: { title, body: readme } }
      : { provider: 'atlassian', action: 'createJiraIssue', summary: `${t('mcpwrite.toJira')}: “${title}” (${key.trim()})`, target: { projectKey: key.trim() }, payload: { summary: title, description: readme } }
    try {
      const r = await api.proposeExternalWrite(sessionId, body)
      // Carry the EXACT target + payload into review so the human authorizes the real bytes (these are
      // what the server-side digest bound — the request body — so showing them never drifts from it).
      setMode({ kind: mode.kind, step: 'review', id: r.id, digest: r.digest, summary: r.summary, target: body.target, payload: body.payload })
      loadHistory()
    } catch (e) { setErr(ApiError.is(e) ? e.message : String(e)) }
    finally { setBusy(false) }
  }

  const confirm = async (): Promise<void> => {
    if (!mode || mode.step !== 'review') return
    setBusy(true); setErr(undefined)
    try {
      const r = await api.confirmExternalWrite(sessionId, mode.id, mode.digest)
      setMode({ kind: mode.kind, step: 'done', ok: r.ok, result: r.result ?? (r.ok ? 'done' : 'failed') })
      loadHistory()
    } catch (e) {
      // A 409 = not connected / unavailable — guide the user to Settings.
      setErr(ApiError.is(e) && e.status === 409 ? t('mcpwrite.notConnected') : ApiError.is(e) ? e.message : String(e))
    } finally { setBusy(false) }
  }

  return (
    <div className="rounded-2xl border border-white/10 bg-white/[0.02] p-4">
      <SectionTitle sub={t('mcpwrite.sub')}>{t('mcpwrite.title')}</SectionTitle>
      {err && <div className="my-2"><ErrorNote>{err}</ErrorNote></div>}

      {/* CONNECTION-AWARE: not connected → guide to Settings instead of a confirm-time 409. */}
      {connected === false && (
        <div className="rounded-lg border border-amber-400/30 bg-amber-400/10 px-3 py-2 text-sm text-amber-200">
          {t('mcpwrite.notConnected')} <Link to="/settings" className="font-semibold underline">{t('mcpwrite.goSettings')}</Link>
        </div>
      )}

      {connected === true && !mode && (
        <div className="flex flex-col gap-2">
          <div className="flex gap-2">
            {/* Confluence is OFFERED only when the connection's live grant includes write:confluence-content
                — otherwise the proposal would mint and then fail at execution. Auto-restores when re-added. */}
            {confluenceAvailable && <Button variant="ghost" onClick={() => open('confluence')}>{t('mcpwrite.toConfluence')}</Button>}
            <Button variant="ghost" onClick={() => open('jira')}>{t('mcpwrite.toJira')}</Button>
          </div>
          {!confluenceAvailable && <div className="text-xs text-slate-500">{t('mcpwrite.confluenceUnavailable')}</div>}
        </div>
      )}

      {connected === true && mode?.step === 'form' && (
        <div className="flex flex-col gap-2">
          <Input value={key} onChange={e => setKey(e.target.value)} placeholder={mode.kind === 'confluence' ? t('mcpwrite.spaceKey') : t('mcpwrite.projectKey')} />
          <div className="flex gap-2">
            <Button onClick={() => void propose()} disabled={busy || !key.trim()}>{busy ? '…' : t('mcpwrite.propose')}</Button>
            <Button variant="ghost" onClick={() => setMode(undefined)}>{t('mcpwrite.cancel')}</Button>
          </div>
        </div>
      )}

      {mode?.step === 'review' && (
        <div className="flex flex-col gap-2">
          <div className="text-sm text-slate-200">{mode.summary}</div>
          {/* EXACT bytes the human authorizes — target + payload that the digest binds. The write
              creates precisely this; nothing is sent that isn't shown here. */}
          <div className="text-xs text-slate-500">{t('mcpwrite.willWrite')}</div>
          <pre className="max-h-48 overflow-auto rounded-lg border border-white/10 bg-black/30 p-2 text-[11px] leading-relaxed text-slate-300 whitespace-pre-wrap break-words">{JSON.stringify({ target: mode.target, payload: mode.payload }, null, 2)}</pre>
          <div className="text-xs text-slate-500">{t('mcpwrite.digest')}: <code>{mode.digest.slice(0, 16)}…</code></div>
          <div className="flex gap-2">
            <Button onClick={() => void confirm()} disabled={busy}>{busy ? '…' : t('mcpwrite.confirm')}</Button>
            <Button variant="ghost" onClick={() => setMode(undefined)}>{t('mcpwrite.cancel')}</Button>
          </div>
        </div>
      )}

      {mode?.step === 'done' && (
        <div role="status" className={`rounded-lg border px-3 py-2 text-sm ${mode.ok ? 'border-[#07D1AF]/30 bg-[#07D1AF]/10 text-[#07D1AF]' : 'border-rose-400/30 bg-rose-400/10 text-rose-300'}`}>
          {mode.ok ? t('mcpwrite.created') : t('mcpwrite.failed')}: {mode.result.slice(0, 200)}
        </div>
      )}

      {/* HISTORY: past proposals + outcomes for this build. */}
      {history.length > 0 && (
        <div className="mt-3 border-t border-white/10 pt-3">
          <div className="mb-1 text-xs font-semibold uppercase tracking-wide text-slate-500">{t('mcpwrite.history')}</div>
          <ul className="flex flex-col gap-1">
            {history.slice().reverse().map(w => (
              <li key={w.id} className="flex items-start gap-2 text-xs text-slate-400">
                <span className={`mt-0.5 shrink-0 rounded px-1.5 py-0.5 font-medium ${w.status === 'executed' ? 'bg-[#07D1AF]/15 text-[#07D1AF]' : w.status === 'failed' ? 'bg-rose-400/15 text-rose-300' : w.status === 'executing' ? 'bg-amber-400/15 text-amber-200' : 'bg-white/10 text-slate-300'}`}>{t(`mcpwrite.st.${w.status}` as 'mcpwrite.st.proposed')}</span>
                <span className="min-w-0 truncate">{w.summary}{w.result ? ` — ${w.result}` : ''}</span>
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  )
}
