import type { LlmProvider, ChatRequest, ChatResult, OnDelta } from '../../LlmProvider.js'

export interface MockConfig {
  /** A fixed reply (e.g. a critic JSON blob) for deterministic tests. */
  reply?: string
}

/** A valid, approved critic review — so the fallback degrades gracefully (no parse crash). */
function defaultCriticJson(isCode: boolean): string {
  return JSON.stringify({
    approved: true,
    overallScore: 80,
    summary: 'mock provider (no real key configured) — auto-approved review',
    findings: [],
    reviewType: isCode ? 'code_review' : 'spec_review',
    iteration: 1,
    hasCriticalFinding: false,
    maxSeverity: 'info',
  })
}

/** A valid Scribe spec JSON so the live agent path works deterministically under the mock. */
function defaultScribeJson(rawIdea: string): string {
  // The agent appends a RAG grounding block to the user content; the mock would
  // otherwise echo it into the title. Use only the original idea (a real LLM writes
  // a clean title regardless). Also cap length so the demo title stays tidy.
  const idea = (rawIdea.split('\n\nRELEVANT PRIOR KNOWLEDGE')[0] ?? rawIdea).trim().slice(0, 80) || 'app'
  return JSON.stringify({
    kind: 'spec',
    title: `Spec for: ${idea}`,
    body: [
      `# ${idea}`, '', '## Problem', idea, '',
      '## Acceptance criteria',
      '- Given the app is open, When the user performs the core action, Then the expected result is shown.',
      '', '## Out of scope', '- Authentication, deployment.',
    ].join('\n'),
  })
}

/** Strip the spec framing the agent prepends, recovering a clean app title. */
function ideaFromProtoPrompt(content: string): string {
  const line = content.split('\n').find(l => l.startsWith('SPEC:')) ?? content
  return line.replace(/^SPEC:\s*/, '').replace(/^Spec for:\s*/i, '').trim().slice(0, 80) || 'AKIS app'
}

/** A valid Proto files JSON so the live agent path works deterministically under the
 *  mock. Emits a SELF-CONTAINED, runnable index.html (→ AppDetector 'static') so the
 *  keyless demo shows a real, themed app live in the preview iframe — not a stub. */
function defaultProtoJson(idea: string): string {
  const safe = idea.replace(/[<>&"]/g, c => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;', '"': '&quot;' }[c]!))
  const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>${safe}</title><style>
:root{color-scheme:dark}
*{box-sizing:border-box}
body{margin:0;min-height:100vh;font-family:ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,sans-serif;color:#e5e7eb;
  background:radial-gradient(1200px 800px at 20% -10%,rgba(56,189,248,.16),transparent 60%),
  radial-gradient(1000px 700px at 110% 10%,rgba(168,85,247,.18),transparent 55%),#05060f;
  display:grid;place-items:center;overflow:hidden}
.stars{position:fixed;inset:0;background-image:radial-gradient(2px 2px at 20% 30%,#fff6,transparent),radial-gradient(1px 1px at 70% 60%,#fff5,transparent),radial-gradient(1.5px 1.5px at 40% 80%,#fff4,transparent),radial-gradient(1px 1px at 85% 25%,#fff5,transparent);
  background-size:300px 300px;animation:drift 90s linear infinite;opacity:.6}
@keyframes drift{to{background-position:300px 300px}}
.card{position:relative;z-index:1;width:min(560px,92vw);padding:40px;border-radius:24px;
  background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.10);backdrop-filter:blur(12px);
  box-shadow:0 0 80px rgba(56,189,248,.10)}
h1{margin:0 0 6px;font-size:30px;background:linear-gradient(90deg,#22d3ee,#a855f7,#f0abfc);-webkit-background-clip:text;background-clip:text;color:transparent}
.tag{font-size:12px;letter-spacing:.2em;text-transform:uppercase;color:#7dd3fc}
.row{display:flex;gap:10px;margin-top:22px}
input{flex:1;padding:12px 14px;border-radius:12px;border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.04);color:#e5e7eb}
button{padding:12px 18px;border:0;border-radius:12px;font-weight:700;color:#05060f;cursor:pointer;background:linear-gradient(90deg,#22d3ee,#a855f7)}
.out{margin-top:18px;min-height:24px;color:#a5f3fc}
.clock{margin-top:18px;font-variant-numeric:tabular-nums;color:#c4b5fd}
footer{margin-top:26px;font-size:12px;color:#64748b}
</style></head>
<body><div class="stars"></div>
<main class="card">
  <div class="tag">Built live by AKIS agents</div>
  <h1>${safe}</h1>
  <p>A working preview generated by the AKIS pipeline. Type something and it responds — real JS running in your browser.</p>
  <div class="row"><input id="i" placeholder="say something…"/><button id="b">Run</button></div>
  <div class="out" id="o"></div>
  <div class="clock" id="c"></div>
  <footer>AKIS · Scribe → Proto → Trace → ship</footer>
</main>
<script>
  const o=document.getElementById('o'),i=document.getElementById('i'),b=document.getElementById('b');
  const run=()=>{o.textContent=i.value?('✦ '+i.value+' — handled by your AKIS app'):'…';};
  b.onclick=run;i.addEventListener('keydown',e=>{if(e.key==='Enter')run();});
  const c=document.getElementById('c');setInterval(()=>{c.textContent=new Date().toLocaleTimeString();},1000);
</script>
</body></html>
`
  return JSON.stringify({ files: [{ filePath: 'index.html', content: html }] })
}

/**
 * Deterministic provider used as the fallback when no real key is configured (or
 * NODE_ENV=test) and as a scriptable backend in tests. No network.
 *
 * IMPORTANT: when no explicit `reply` is set and the request looks like a critic
 * review (the only production consumer), the default is VALID critic JSON — so a
 * keyless production fallback degrades gracefully instead of throwing a JSON
 * parse error on every session.
 */
export class MockProvider implements LlmProvider {
  readonly name = 'mock'
  readonly model = 'mock'
  constructor(private cfg: MockConfig = {}) {}

  async chat(req: ChatRequest): Promise<ChatResult> {
    if (this.cfg.reply !== undefined) {
      return { text: this.cfg.reply, usage: { inTokens: 0, outTokens: 0 } }
    }
    // Role-appropriate parseable JSON so the LIVE agent path works under the mock.
    const sys = req.system.toLowerCase()
    const last = req.messages[req.messages.length - 1]?.content ?? ''
    if (sys.includes('reviewer')) {
      return { text: defaultCriticJson(sys.includes('code reviewer')), usage: { inTokens: 0, outTokens: 0 } }
    }
    if (sys.includes('scribe')) {
      // The idea is the last user message; keep it for the spec title.
      return { text: defaultScribeJson(last || 'app'), usage: { inTokens: 0, outTokens: 0 } }
    }
    if (sys.includes('proto')) {
      return { text: defaultProtoJson(ideaFromProtoPrompt(last)), usage: { inTokens: 0, outTokens: 0 } }
    }
    return { text: `mock: ${last.slice(0, 40)}`, usage: { inTokens: 0, outTokens: 0 } }
  }

  /**
   * Stream the SAME deterministic reply as `chat`, chopped into a few word-grouped
   * deltas so the keyless demo (and the FE incremental-render tests) exercise the
   * real streaming path. The concatenation of all deltas equals `chat().text` exactly,
   * so spec detection on the accumulated text behaves identically to the non-stream path.
   */
  async chatStream(req: ChatRequest, onDelta: OnDelta): Promise<ChatResult> {
    const result = await this.chat(req)
    const full = result.text ?? ''
    for (const piece of chunkText(full)) onDelta(piece)
    return result
  }
}

/** Split text into a handful of contiguous, gap-preserving chunks (3-word groups). */
function chunkText(text: string): string[] {
  if (!text) return []
  // Split keeping the whitespace with each token, so join('') reproduces the input.
  const tokens = text.match(/\s*\S+/g) ?? [text]
  const out: string[] = []
  for (let i = 0; i < tokens.length; i += 3) out.push(tokens.slice(i, i + 3).join(''))
  return out
}
